# .yaml files used to store configuration settings
model:
  base_learning_rate: 8.0e-5 # 1.5e-04
  scale_fr : False
  target: lvdm.models.ddpm3d.FrameInterpPredLatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: "image"
    image_size: 32
    channels: 4
    monitor: val/loss_simple_ema
    conditioning_key: concat-adm-mask
    cond_stage_config: null
    noisy_cond: True
    max_noise_level: 250
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: False
    scale_factor: 0.33422927
    shift_factor: 1.4606637
    encoder_type: 3d
    rand_temporal_mask: true
    p_interp: 0.9
    p_pred: 0.9
    n_prevs: null
    split_clips: False
    downfactor_t : null # used for split video frames to clips before encoding
    clip_length: null 

    unet_config:
      target: lvdm.models.modules.openaimodel3d.FrameInterpPredUNet
      params: 
        num_classes: 251 # time steps for noise conditioning 
        image_size: 32
        in_channels: 5
        out_channels: 256
        attention_resolutions: 
        - 8
        - 4
        - 2
        num_res_blocks: 3
        channel_mult:
        - 1
        




